"""Clean up helpers for the meshes generated by the Creators Tools.

A cage is generated by copying, or by tracing, a mesh of the model, and it
inherits all of its data: UV Maps, color attributes, shape keys, and one vertex
group per bone of the Armature. None of this is read by the simulation, and it
is only carried around in the file.
"""

import bpy

# Try NumPy
try:
    import numpy as np

    USE_NUMPY = True
except ImportError:
    USE_NUMPY = False

# Weights below this do not deform anything
WEIGHT_THRESHOLD = 1e-4

# Distance below which two shapes are considered to be the same one
SHAPE_KEY_THRESHOLD = 1e-6

# A vertex group is not always read through a property called 'vertex_group': the
# name of every property holding one contains it, though
VERTEX_GROUP_KEYWORD = "vertex_group"

# Collections longer than this are data, not settings, and are not searched
MAX_WALKED_COLLECTION = 32


def clear_attributes(obj):
    """Remove the UV Maps and the custom attributes of the mesh 'obj'."""

    mesh = obj.data

    while mesh.uv_layers:
        mesh.uv_layers.remove(mesh.uv_layers[0])

    # Vertex groups can be exposed as attributes as well: together with the
    # required and the internal ones (positions, selection, ...) they are the
    # only attributes which are kept, as removing them would break the modifiers
    # using them
    vertex_groups = {x.name for x in obj.vertex_groups}
    for name in [x.name for x in mesh.attributes]:
        attribute = mesh.attributes.get(name)
        if attribute is None or attribute.is_required or attribute.is_internal:
            continue
        if name in vertex_groups:
            continue
        mesh.attributes.remove(attribute)


def _coordinates(data, count):
    """The 'co' of a shape key or of the vertices of a mesh, as a flat buffer."""

    values = np.empty(count * 3, dtype=np.float32) if USE_NUMPY else [0.0] * (count * 3)
    data.foreach_get("co", values)
    return values


def _same_coordinates(first, second):
    """True when no coordinate of the two buffers differs by more than the threshold."""

    if USE_NUMPY:
        return bool(np.all(np.abs(first - second) <= SHAPE_KEY_THRESHOLD))
    return all(abs(a - b) <= SHAPE_KEY_THRESHOLD for a, b in zip(first, second))


def shape_key_is_void(key_block):
    """True when 'key_block' does not move a single vertex of its mesh."""

    shape_keys = key_block.id_data

    # Absolute shape keys are interpolated one into the next, so a key identical
    # to its neighbour is still a step of the sequence: only relative keys can be
    # told to be void by comparing them to the shape they are relative to
    if not shape_keys.use_relative:
        return False

    reference = shape_keys.reference_key
    if key_block == reference:
        return False

    relative = key_block.relative_key or reference
    count = len(key_block.data)

    return _same_coordinates(
        _coordinates(key_block.data, count), _coordinates(relative.data, count)
    )


def remove_shape_key(obj, key_block):
    """Remove 'key_block' from 'obj', together with the drivers pointing at it."""

    shape_keys = key_block.id_data
    animation_data = shape_keys.animation_data

    if animation_data is not None:
        # The path of the key itself, 'key_blocks["Name"]', is the prefix of the
        # path of each one of its properties. Taken from Blender and not built
        # from the name, so that the quotes of a name are escaped the same way
        prefix = key_block.path_from_id()
        for fcurve in [x for x in animation_data.drivers if x.data_path.startswith(prefix)]:
            animation_data.drivers.remove(fcurve)

    obj.shape_key_remove(key_block)


def clear_shape_keys(obj, void_only=False):
    """Remove the shape keys of the mesh 'obj'."""

    shape_keys = obj.data.shape_keys
    if shape_keys is None:
        return 0

    if not void_only:
        removed = len(shape_keys.key_blocks)
        obj.shape_key_clear()
        return removed

    count = len(obj.data.vertices)
    removed = 0

    for key_block in list(shape_keys.key_blocks):
        if shape_key_is_void(key_block):
            remove_shape_key(obj, key_block)
            removed += 1

    shape_keys = obj.data.shape_keys
    if shape_keys is not None and len(shape_keys.key_blocks) == 1:
        basis = shape_keys.key_blocks[0]
        if _same_coordinates(
            _coordinates(basis.data, count), _coordinates(obj.data.vertices, count)
        ):
            remove_shape_key(obj, basis)
            removed += 1

    return removed


def _vertex_group_properties(data, names, depth=3):
    """Fill 'names' with the value of every 'vertex_group' property found in 'data'."""

    if data is None or depth < 0:
        return

    for prop in data.bl_rna.properties:
        identifier = prop.identifier

        if identifier == "rna_type":
            continue

        if prop.type == "STRING":
            if VERTEX_GROUP_KEYWORD in identifier:
                value = getattr(data, identifier, "")
                if value:
                    names.add(value)
            continue

        if depth <= 0:
            continue

        value = getattr(data, identifier, None)

        # Datablocks are never walked: a vertex group belongs to the object owning
        # the settings, so the search never has to leave it
        if prop.type == "POINTER":
            if value is not None and not isinstance(value, bpy.types.ID):
                _vertex_group_properties(value, names, depth - 1)

        elif prop.type == "COLLECTION" and value is not None:
            # Only the small settings collections are walked: the data ones
            # (particles, points, ...) can not hold a vertex group name
            if len(value) <= MAX_WALKED_COLLECTION:
                for entry in value:
                    if not isinstance(entry, bpy.types.ID):
                        _vertex_group_properties(entry, names, depth - 1)


def _constraint_subtargets(constraint, obj, names):
    """Fill 'names' with the subtargets of 'constraint' pointing at the mesh 'obj'."""

    # The Armature constraint holds a list of targets, the others a single one
    targets = getattr(constraint, "targets", None)

    for entry in list(targets) if targets is not None else [constraint]:
        if getattr(entry, "target", None) is obj:
            subtarget = getattr(entry, "subtarget", "")
            if subtarget:
                names.add(subtarget)


def collect_used_vertex_groups(obj):
    """The names of the vertex groups of 'obj' which are read by something."""

    names = set()

    for modifier in obj.modifiers:
        _vertex_group_properties(modifier, names)

        # Geometry Nodes read the groups as named attributes, whose names are stored
        # as custom properties of the modifier
        for value in modifier.values():
            if isinstance(value, str) and value:
                names.add(value)

    for particle_system in obj.particle_systems:
        _vertex_group_properties(particle_system, names)

    _vertex_group_properties(obj.soft_body, names)

    shape_keys = obj.data.shape_keys
    if shape_keys is not None:
        for key_block in shape_keys.key_blocks:
            if key_block.vertex_group:
                names.add(key_block.vertex_group)

    # A constraint whose target is a mesh uses one of its vertex groups as the
    # subtarget, and it can live on any object, or on any bone, of the file
    for other in bpy.data.objects:
        for constraint in other.constraints:
            _constraint_subtargets(constraint, obj, names)

        if other.pose is not None:
            for bone in other.pose.bones:
                for constraint in bone.constraints:
                    _constraint_subtargets(constraint, obj, names)

    return names


def clear_unused_vertex_groups(obj, keep=()):
    """Remove the vertex groups of 'obj' which do not weight a single vertex."""

    used = set()
    for vertex in obj.data.vertices:
        for element in vertex.groups:
            if element.weight > WEIGHT_THRESHOLD:
                used.add(element.group)

    preserved = set(keep) | collect_used_vertex_groups(obj)

    removed = [x for x in obj.vertex_groups if x.index not in used and x.name not in preserved]
    for group in removed:
        obj.vertex_groups.remove(group)

    return len(removed)
