"""Clean up helpers for the meshes generated by the Creators Tools.

A cage is generated by copying, or by tracing, a mesh of the model, and it
inherits all of its data: UV Maps, color attributes, shape keys, and one vertex
group per bone of the Armature. None of this is read by the simulation, and it
is only carried around in the file.
"""

# Try NumPy
try:
    import numpy as np

    USE_NUMPY = True
except ImportError:
    USE_NUMPY = False

# Weights below this do not deform anything
WEIGHT_THRESHOLD = 1e-4

# Distance below which two shapes are considered to be the same one
SHAPE_KEY_THRESHOLD = 1e-6


def clear_attributes(obj):
    """Remove the UV Maps and the custom attributes of the mesh 'obj'."""

    mesh = obj.data

    while mesh.uv_layers:
        mesh.uv_layers.remove(mesh.uv_layers[0])

    # Vertex groups can be exposed as attributes as well: together with the
    # required and the internal ones (positions, selection, ...) they are the
    # only attributes which are kept, as removing them would break the modifiers
    # using them
    vertex_groups = {x.name for x in obj.vertex_groups}
    for name in [x.name for x in mesh.attributes]:
        attribute = mesh.attributes.get(name)
        if attribute is None or attribute.is_required or attribute.is_internal:
            continue
        if name in vertex_groups:
            continue
        mesh.attributes.remove(attribute)


def _coordinates(data, count):
    """The 'co' of a shape key or of the vertices of a mesh, as a flat buffer."""

    values = np.empty(count * 3, dtype=np.float32) if USE_NUMPY else [0.0] * (count * 3)
    data.foreach_get("co", values)
    return values


def _same_coordinates(first, second):
    """True when no coordinate of the two buffers differs by more than the threshold."""

    if USE_NUMPY:
        return bool(np.all(np.abs(first - second) <= SHAPE_KEY_THRESHOLD))
    return all(abs(a - b) <= SHAPE_KEY_THRESHOLD for a, b in zip(first, second))


def shape_key_is_void(key_block):
    """True when 'key_block' does not move a single vertex of its mesh."""

    shape_keys = key_block.id_data

    # Absolute shape keys are interpolated one into the next, so a key identical
    # to its neighbour is still a step of the sequence: only relative keys can be
    # told to be void by comparing them to the shape they are relative to
    if not shape_keys.use_relative:
        return False

    reference = shape_keys.reference_key
    if key_block == reference:
        return False

    relative = key_block.relative_key or reference
    count = len(key_block.data)

    return _same_coordinates(
        _coordinates(key_block.data, count), _coordinates(relative.data, count)
    )


def remove_shape_key(obj, key_block):
    """Remove 'key_block' from 'obj', together with the drivers pointing at it."""

    shape_keys = key_block.id_data
    animation_data = shape_keys.animation_data

    if animation_data is not None:
        # The path of the key itself, 'key_blocks["Name"]', is the prefix of the
        # path of each one of its properties. Taken from Blender and not built
        # from the name, so that the quotes of a name are escaped the same way
        prefix = key_block.path_from_id()
        for fcurve in [x for x in animation_data.drivers if x.data_path.startswith(prefix)]:
            animation_data.drivers.remove(fcurve)

    obj.shape_key_remove(key_block)


def clear_shape_keys(obj, void_only=False):
    """Remove the shape keys of the mesh 'obj'."""

    shape_keys = obj.data.shape_keys
    if shape_keys is None:
        return 0

    if not void_only:
        removed = len(shape_keys.key_blocks)
        obj.shape_key_clear()
        return removed

    count = len(obj.data.vertices)
    removed = 0

    for key_block in list(shape_keys.key_blocks):
        if shape_key_is_void(key_block):
            remove_shape_key(obj, key_block)
            removed += 1

    shape_keys = obj.data.shape_keys
    if shape_keys is not None and len(shape_keys.key_blocks) == 1:
        basis = shape_keys.key_blocks[0]
        if _same_coordinates(
            _coordinates(basis.data, count), _coordinates(obj.data.vertices, count)
        ):
            remove_shape_key(obj, basis)
            removed += 1

    return removed


def clear_unused_vertex_groups(obj, keep=()):
    """Remove the vertex groups of 'obj' which do not weight a single vertex."""

    used = set()
    for vertex in obj.data.vertices:
        for element in vertex.groups:
            if element.weight > WEIGHT_THRESHOLD:
                used.add(element.group)

    preserved = set(keep)
    for modifier in obj.modifiers:
        name = getattr(modifier, "vertex_group", "")
        if name:
            preserved.add(name)

    removed = [x for x in obj.vertex_groups if x.index not in used and x.name not in preserved]
    for group in removed:
        obj.vertex_groups.remove(group)

    return len(removed)
