import bpy

from .. import __package__ as base_package
from ..model_selection.active_object import (
    active_object_operator_poll,
    mustardui_active_object,
)


class MustardUI_Armature_SmartCheck(bpy.types.Operator):
    """Check if a known armature type (ARP, Rigify, MHX) is available, and automatically set the Armature panel"""  # noqa: E501

    bl_idname = "mustardui.armature_smartcheck"
    bl_label = "Armature Smart Check"
    bl_options = {"UNDO"}

    reset_current_collections: bpy.props.BoolProperty(
        name="Reset Current Bone Collections",
        default=True,
        description="If disabled, do not remote the current enabled bone "
        "collections from the UI.\nNote that the bone "
        "collections not added to the UI will not be "
        "preserved, i.e., in case they are generated by "
        "default for the armature data type (ARP, Rigify, "
        "MHX)",
    )

    @classmethod
    def poll(cls, context):
        return active_object_operator_poll(context, config=1)

    def execute(self, context):

        res, obj = mustardui_active_object(context, config=1)
        rig_settings = obj.MustardUI_RigSettings
        addon_prefs = context.preferences.addons[base_package].preferences

        if rig_settings.model_armature_object is None:
            self.report(
                {"WARNING"},
                "MustardUI - An error occurred while using Armature Smart Check. "
                "End Configuration, re-enter Configuration mode and re-try",
            )

        found_type = ""
        found_colls = 0

        # Standard armature setup
        # Format: Collection name, name to change, icon, default
        preset_bone_collections = []

        # Auto-Rig Pro
        if hasattr(obj, '["arp_updated"]') and obj["arp_updated"] != "":
            if addon_prefs.debug:
                print(
                    "\nMustardUI - Smart Check - Found an ARP rig, version: '"
                    + obj["arp_updated"]
                    + "' ."
                )

            preset_bone_collections = [
                ("Main", "", "", True),
                ("Secondary", "", "", False),
            ]

            found_type = "ARP"

        # Rigify
        elif hasattr(obj, '["rig_id"]') and obj["rig_id"] != "":
            if addon_prefs.debug:
                print(
                    "\nMustardUI - Smart Check - Found a Rigify rig, setting layers "
                    "for Rigify."
                )

            # Collection name, name to change, icon, default
            preset_bone_collections = [
                ("Face", "", "USER", True),
                ("Face (Primary)", "", "USER", False),
                ("Torso", "", "", True),
                ("Torso (Tweak)", "", "", False),
                ("Fingers", "", "", True),
                ("Fingers (Detail)", "", "", False),
                ("Arm.L (IK)", "IK Arm Left", "", True),
                ("Arm.R (IK)", "IK Arm Right", "", True),
                ("Arm.L (FK)", "FK Arm Left", "", False),
                ("Arm.R (FK)", "FK Arm Right", "", False),
                ("Arm.L (Tweak)", "Tweak Arm Left", "", False),
                ("Arm.R (Tweak)", "Tweak Arm Right", "", False),
                ("Leg.L (IK)", "IK Leg Left", "", True),
                ("Leg.R (IK)", "IK Leg Right", "", True),
                ("Leg.L (FK)", "FK Leg Left", "", False),
                ("Leg.R (FK)", "FK Leg Right", "", False),
                ("Leg.L (Tweak)", "Tweak Leg Left", "", False),
                ("Leg.R (Tweak)", "Tweak Leg Right", "", False),
                ("Root", "", "", True),
            ]

            # Mirror option enabled
            obj.MustardUI_ArmatureSettings.mirror = True

            found_type = "Rigify"

        # MHX Rig
        elif hasattr(rig_settings.model_armature_object, '["MhxRig"]'):
            if addon_prefs.debug:
                print(
                    "\nMustardUI - Smart Check - Found a MHX rig, setting layers "
                    "for MHX."
                )

            # Collection name, name to change, icon, default
            preset_bone_collections = [
                ("Head", "", "USER", True),
                ("Face", "", "USER", False),
                ("Spine 2", "Spine", "", True),
                ("Spine", "Spine Advanced", "", False),
                ("IK Arm Left", "", "", True),
                ("IK Arm Right", "", "", True),
                ("FK Arm Left", "", "", False),
                ("FK Arm Right", "", "", False),
                ("Hand Left", "", "", False),
                ("Hand Right", "", "", False),
                ("Fingers Left", "", "", False),
                ("Fingers Right", "", "", False),
                ("IK Leg Left", "", "", True),
                ("IK Leg Right", "", "", True),
                ("FK Leg Left", "", "", False),
                ("FK Leg Right", "", "", False),
                ("Toes Left", "", "", False),
                ("Toes Right", "", "", False),
                ("Tweak", "", "", False),
                ("Root", "", "", True),
            ]

            # Mirror option enabled
            obj.MustardUI_ArmatureSettings.mirror = True

            found_type = "MHX"

        # Generic keyword-based auto-selection for unrecognised rigs
        else:
            # Keywords that flag internal/infrastructure collections to skip
            _SKIP = ("rig_bones", "detail_layer", "base_layer", "detail")
            # (keyword, icon, default) — FK-only names are caught by the IK check below
            _RULES = [
                ("face", "USER", True),
                ("jiggle", "", True),
                ("ik", "", True),
                ("fk", "", False),
                ("spine", "", True),
                ("hand", "", True),
                ("root", "", True),
                ("base", "", True),
            ]
            import re as _re

            _MIRROR_RE = _re.compile(
                r"(^[LR][_.]|[_.][LR]$|[_.][LR][_.]"
                r"|\bright\b|\bleft\b"
                r"|_right|_left|right_|left_)",
                _re.IGNORECASE,
            )
            for coll in obj.collections_all:
                n = coll.name.lower()
                if any(kw in n for kw in _SKIP):
                    continue
                for keyword, icon, default in _RULES:
                    if keyword in n:
                        # FK-only collections default off even if spine/hand also matches
                        resolved_default = (
                            False if ("fk" in n and "ik" not in n) else default
                        )
                        preset_bone_collections.append(
                            (coll.name, "", icon, resolved_default)
                        )
                        if addon_prefs.debug:
                            print(
                                f"\nMustardUI - Smart Check - Keyword '{keyword}' "
                                f"matched '{coll.name}'."
                            )
                        break

            # Sort: face/head → arms → legs → rest
            def _sort_key(entry):
                n = entry[0].lower()
                if any(kw in n for kw in ("face", "head")):
                    return 0
                if any(
                    kw in n
                    for kw in ("arm", "hand", "finger", "elbow", "shoulder", "wrist")
                ):
                    return 1
                if any(
                    kw in n
                    for kw in ("spine", "torso", "chest", "back", "abdomen", "waist")
                ):
                    return 2
                if any(
                    kw in n
                    for kw in ("leg", "foot", "feet", "toe", "knee", "hip", "thigh")
                ):
                    return 3
                if any(kw in n for kw in ("root", "base")):
                    return 4
                return 5

            preset_bone_collections.sort(key=_sort_key)

            if any(_MIRROR_RE.search(c.name) for c in obj.collections_all):
                obj.MustardUI_ArmatureSettings.mirror = True

        # Apply preset
        if len(preset_bone_collections) > 0:
            obj.MustardUI_ArmatureSettings.mirror = True

            # Reset current armature visibility options
            if self.reset_current_collections:
                for coll in obj.collections_all:
                    coll.MustardUI_ArmatureBoneCollection.is_in_UI = False

            # Apply new preset
            for preset in reversed(preset_bone_collections):
                for coll in obj.collections_all:
                    if coll.name == preset[0] or coll.name == preset[1]:
                        if preset[1] != "":
                            coll.name = preset[1]
                        coll.MustardUI_ArmatureBoneCollection.is_in_UI = True
                        coll.MustardUI_ArmatureBoneCollection.default = preset[3]
                        if preset[2] != "":
                            coll.MustardUI_ArmatureBoneCollection.icon = preset[2]
                        if addon_prefs.debug:
                            print(
                                "\nMustardUI - Smart Check - Armature layer "
                                + str(preset[0])
                                + " set."
                            )
                        obj.collections.move(coll.index, 0)
                        found_colls += 1

        # Check for Outfit/Hair/Extras switcher
        outfits = 0
        outfit_colls = [
            x.collection for x in rig_settings.outfits_collections if x.collection
        ]
        if rig_settings.extras_collection is not None:
            outfit_colls.append(rig_settings.extras_collection)
        if rig_settings.hair_collection is not None:
            outfit_colls.append(rig_settings.hair_collection)
        for coll in outfit_colls:
            for o in coll.objects:
                for bcoll in obj.collections_all:
                    if bcoll.name == o.name:
                        bcArmatureBoneCollection = (
                            bcoll.MustardUI_ArmatureBoneCollection
                        )
                        bcArmatureBoneCollection.is_in_UI = True
                        bcArmatureBoneCollection.outfit_switcher_enable = True
                        bcArmatureBoneCollection.outfit_switcher_collection = coll
                        bcArmatureBoneCollection.outfit_switcher_object = o
                        if addon_prefs.debug:
                            print(
                                "\nMustardUI - Smart Check - Armature layer "
                                + bcoll.name
                                + " added as Outfit Switcher."
                            )
                        outfits += 1

        if found_type != "" and not outfits:
            if found_colls > 0:
                self.report(
                    {"INFO"},
                    f"MustardUI - Smart Check found {found_colls} collections in a "
                    f"'{found_type}' armature.",
                )
            else:
                self.report(
                    {"WARNING"},
                    f"MustardUI - Smart Check found a '{found_type}' armature but no "
                    f"viable collection.",
                )
        elif found_type == "" and found_colls > 0 and not outfits:
            self.report(
                {"INFO"},
                f"MustardUI - Smart Check auto-selected {found_colls} bone "
                f"collection(s) for an unknown Armature type.",
            )
        elif outfits:
            self.report(
                {"INFO"}, "MustardUI - Outfits Switcher bone collections were added."
            )
        else:
            self.report(
                {"WARNING"},
                "MustardUI - Smart Check found no compatible armature. No collection "
                "has been added.",
            )

        return {"FINISHED"}

    def invoke(self, context, event):
        return context.window_manager.invoke_props_dialog(self, width=450)

    def draw(self, context):

        layout = self.layout

        layout.prop(self, "reset_current_collections")


def register():
    bpy.utils.register_class(MustardUI_Armature_SmartCheck)


def unregister():
    bpy.utils.unregister_class(MustardUI_Armature_SmartCheck)
