import os

import bpy
from bpy.props import BoolProperty, EnumProperty, IntProperty, StringProperty

from ..model_selection.active_object import (
    active_object_operator_poll,
    mustardui_active_object,
)

# Name prefix of the preview images generated by this operator
PREVIEW_PREFIX = "MustardUI Preview - "


def find_view3d(context):
    """Return the (area, region) of the 3D Viewport to render from, or (None, None)"""

    areas = []
    if context.area is not None and context.area.type == "VIEW_3D":
        areas.append(context.area)
    if context.screen is not None:
        areas += [x for x in context.screen.areas if x.type == "VIEW_3D"]

    for area in areas:
        for region in area.regions:
            if region.type == "WINDOW":
                return area, region

    return None, None


def set_attributes(values):
    """Set (owner, attribute, value) triples, skipping values not valid in the current
    state (e.g. a color depth not supported by the file format)"""

    for owner, attr, value in values:
        try:
            setattr(owner, attr, value)
        except (TypeError, ValueError):
            pass


class MustardUI_Outfits_RenderPreview(bpy.types.Operator):
    """Render the Outfits previews from the 3D Viewport or the scene Camera.\nEach Outfit is shown in turn, rendered, and stored as an image packed in the .blend file"""  # noqa: E501

    bl_idname = "mustardui.outfits_render_preview"
    bl_label = "Render Outfit Previews"
    bl_options = {"UNDO"}

    outfit: StringProperty(
        default="",
        description="Outfit to render.\nLeave empty to render all the Outfits",
        options={"HIDDEN", "SKIP_SAVE"},
    )

    resolution: IntProperty(
        default=1024,
        min=32,
        max=1024,
        name="Resolution",
        description="Size of the square preview image.\nLarger values give sharper "
        "previews at large Preview Scales, but increase the .blend file size",
    )

    use_camera: BoolProperty(
        default=False,
        name="Use Scene Camera",
        description="Render from the scene Camera instead of the 3D Viewport view",
    )

    transparent: BoolProperty(
        default=True,
        name="Transparent Background",
        description="Render the background as transparent",
    )

    shading: EnumProperty(
        default="SOLID",
        items=(
            ("SOLID", "Solid", "Render with Solid shading", "SHADING_SOLID", 0),
            (
                "SOLID_TEXTURE",
                "Texture",
                "Render with Solid shading, using the material textures as colors",
                "TEXTURE",
                1,
            ),
            (
                "EEVEE",
                "EEVEE",
                "Render with EEVEE, using the scene lights and World",
                "SHADING_RENDERED",
                2,
            ),
        ),
        name="Shading",
        description="Shading used to render the previews",
    )

    def draw(self, context):
        layout = self.layout
        layout.row().prop(self, "shading", expand=True)
        col = layout.column()
        col.prop(self, "resolution")
        col.prop(self, "use_camera")
        col.prop(self, "transparent")

    @classmethod
    def poll(cls, context):
        return (
            active_object_operator_poll(context, config=1) and find_view3d(context)[0] is not None
        )

    def invoke(self, context, event):
        return context.window_manager.invoke_props_dialog(self)

    def execute(self, context):

        res, arm = mustardui_active_object(context, config=1)
        rig_settings = arm.MustardUI_RigSettings
        scene = context.scene

        if self.use_camera and scene.camera is None:
            self.report({"ERROR"}, "MustardUI - The scene has no Camera.")
            return {"CANCELLED"}

        outfits = {x.collection.name: x for x in rig_settings.outfits_collections if x.collection}

        if self.outfit == "":
            names = (["Nude"] if rig_settings.outfit_nude else []) + list(outfits)
        elif self.outfit in outfits or (self.outfit == "Nude" and rig_settings.outfit_nude):
            names = [self.outfit]
        else:
            self.report({"ERROR"}, f'MustardUI - Outfit "{self.outfit}" not found.')
            return {"CANCELLED"}

        area, region = find_view3d(context)
        render = scene.render
        image_settings = render.image_settings

        # Render settings, applied in order and restored in the same order
        render_settings = [
            (render, "resolution_x", self.resolution),
            (render, "resolution_y", self.resolution),
            (render, "resolution_percentage", 100),
            (render, "film_transparent", self.transparent),
        ]
        if hasattr(image_settings, "media_type"):
            render_settings.append((image_settings, "media_type", "IMAGE"))
        render_settings += [
            (image_settings, "file_format", "PNG"),
            (image_settings, "color_mode", "RGBA"),
            (image_settings, "color_depth", "8"),
        ]

        # Always render with the Viewport context, since rendering from the scene Camera
        # without it ignores the shading and uses Solid. The Camera is used by switching
        # the Viewport to Camera view. Overlays are hidden, otherwise they are rendered
        space = area.spaces.active
        render_settings.append((space.overlay, "show_overlays", False))
        if self.use_camera:
            # Entering Camera view changes the view rotation: restore the view after it
            rv3d = space.region_3d
            render_settings += [
                (rv3d, "view_perspective", "CAMERA"),
                (rv3d, "view_rotation", rv3d.view_rotation.copy()),
                (rv3d, "view_location", rv3d.view_location.copy()),
                (rv3d, "view_distance", rv3d.view_distance),
            ]

        if self.shading == "EEVEE":
            engine = "BLENDER_EEVEE" if bpy.app.version >= (5, 0, 0) else "BLENDER_EEVEE_NEXT"
            render_settings += [(render, "engine", engine), (space.shading, "type", "RENDERED")]
        else:
            color_type = "TEXTURE" if self.shading == "SOLID_TEXTURE" else "MATERIAL"
            render_settings += [
                (space.shading, "type", "SOLID"),
                (space.shading, "color_type", color_type),
            ]

        # Copy vectors and quaternions, which otherwise follow the live values
        saved_settings = []
        for owner, attr, _ in render_settings:
            value = getattr(owner, attr)
            saved_settings.append((owner, attr, value.copy() if hasattr(value, "copy") else value))
        current_outfit = rig_settings.outfits_list

        rendered = 0
        set_attributes(render_settings)

        try:
            for name in names:
                # Switching the outfit updates the visibility of the model
                if rig_settings.outfits_list != name:
                    rig_settings.outfits_list = name

                with context.temp_override(area=area, region=region):
                    bpy.ops.render.opengl(view_context=True)

                render_result = bpy.data.images.get("Render Result")
                if render_result is None:
                    self.report({"ERROR"}, "MustardUI - The Viewport render failed.")
                    return {"CANCELLED"}

                # Render Result pixels can not be copied: save to disk, load and pack
                filepath = os.path.join(bpy.app.tempdir, f"mustardui_preview_{rendered}.png")
                render_result.save_render(filepath, scene=scene)
                image = bpy.data.images.load(filepath)
                image.pack()
                os.remove(filepath)

                # Assign the new preview and clean up the one previously rendered
                if name == "Nude":
                    old_image = rig_settings.outfit_nude_preview
                    rig_settings.outfit_nude_preview = image
                else:
                    old_image = outfits[name].preview
                    outfits[name].preview = image

                if (
                    old_image is not None
                    and old_image.name.startswith(PREVIEW_PREFIX)
                    and old_image.users == 0
                ):
                    bpy.data.images.remove(old_image)

                image.name = PREVIEW_PREFIX + name
                rendered += 1

        finally:
            if rig_settings.outfits_list != current_outfit:
                rig_settings.outfits_list = current_outfit
            set_attributes(saved_settings)

        self.report({"INFO"}, f"MustardUI - {rendered} Outfit previews rendered.")

        return {"FINISHED"}


def register():
    bpy.utils.register_class(MustardUI_Outfits_RenderPreview)


def unregister():
    bpy.utils.unregister_class(MustardUI_Outfits_RenderPreview)
