name: Build & Test Blender Extension

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  blender-51:
    uses: Mustard2/blender-workflows/.github/workflows/blender-build.yml@v1
    with:
      timeout-seconds: 180
      blender-version: "5.1.0"
  blender-42:
    uses: Mustard2/blender-workflows/.github/workflows/blender-build.yml@v1
    with:
      timeout-seconds: 180
      blender-version: "4.2.0"
