name: Build & Test Blender Extension

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  blender:
    uses: Mustard2/blender-workflows/.github/workflows/blender-build.yml@v1
    with:
      timeout-seconds: 180
