name: Run in Custom Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: linuxserver/blender:4.4.1
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
