name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://mirror.blender.org/ftp/sergey/ci/blender-headless-linux-x64.tar.xz
          tar -xf blender-headless-linux-x64.tar.xz
          export PATH=$PATH:$(pwd)/blender-headless-linux-x64
          blender --version  # Check Blender installation
          pip install pylint
          python -m pip install --user bpy  # This should work after installing Blender
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
