name: Run in Custom Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: lscr.io/linuxserver/blender:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          blender --version  # Check Blender installation
          python -m pip install --user bpy
          pip3 install pylint

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
