name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Ruff
        run: pip install ruff

      - name: Lint with Ruff
        run: ruff check .

      - name: Check formatting with Ruff
        run: ruff format --check .

  blender-51:
    needs: lint
    uses: Mustard2/blender-workflows/.github/workflows/blender-build.yml@v1
    with:
      timeout-seconds: 180
      blender-version: "5.1.0"

  blender-42:
    needs: lint
    uses: Mustard2/blender-workflows/.github/workflows/blender-build.yml@v1
    with:
      timeout-seconds: 180
      blender-version: "4.2.0"
