name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Formatting and Linting

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Ruff
        run: pip install ruff

      - name: Lint with Ruff
        run: ruff check .

      - name: Check formatting with Ruff
        run: ruff format --check .

  blender:
    strategy:
      matrix:
        blender: [ "5.1.0", "4.5.8", "4.2.19" ]

    name: Blender ${{ matrix.blender }}
    needs: lint
    uses: Mustard2/blender-workflows/.github/workflows/blender-build.yml@v3
    with:
      timeout-seconds: 180
      blender-version: ${{ matrix.blender }}
